services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: ['doctrine.event_subscriber']

    App\EventSubscriber\:
        resource: '../../src/EventSubscriber'
