services:
    nginx:
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${HTTP_HOST}`)"
        networks:
            - traefik

    rabbitmq:
        environment:
            RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management path_prefix "/rabbitmq"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}-rabbitmq.loadbalancer.server.port=15672"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rabbitmq.rule=Host(`${HTTP_HOST}`) && PathPrefix(`/rabbitmq`)"
        networks:
            - traefik

    mailhog:
        environment:
            MH_UI_WEB_PATH: /mailhog
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}-mailhog.loadbalancer.server.port=8025"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mailhog.rule=Host(`${HTTP_HOST}`) && PathPrefix(`/mailhog`)"
        networks:
            - traefik

    adminer:
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}-adminer.loadbalancer.server.port=8080"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-adminer.rule=Host(`${HTTP_HOST}`) && PathPrefix(`/adminer`)"
        networks:
            - traefik

networks:
    traefik:
        external:
            name: ${TRAEFIK_NETWORK}
