dependencies:
    services:
        - name: mysql
          host: mysql # override by terraform
          port: 3306 # override by terraform
        - name: rabbitmq
          host: rabbitmq # override by terraform
          port: 5672 # override by terraform
        - name: redis
          host: redis # override by terraform
          port: 6379 # override by terraform
metrics:
    enabled: true
migrations:
    - name: doctrine
      command: bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction
      timeout: 60
    - name: messenger
      command: bin/console messenger:setup-transports --no-interaction
      timeout: 10
web:
    nginx:
        config:
            sharedPublicFiles:
                enabled: true
    phpfpm:
        customLivenessProbe: |-
            exec:
                command:
                    - php-fpm-healthcheck
                    - --listen-queue=10
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 1
            successThreshold: 1
        customReadinessProbe: |-
            exec:
                command:
                    - php-fpm-healthcheck
                    - --listen-queue=5
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 1
            successThreshold: 1
workers:
    - name: messenger
      replica: 3
      command: bin/console messenger:consume --memory-limit=128M --time-limit=3600
