name: Security

on:
    schedule:
        - cron:  '0 6 * * *'

    pull_request:

jobs:
    symfony_security_checker:
        name: Symfony Security Checker
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name : run symfony security-checker
              uses: symfonycorp/security-checker-action@v2
